// Code generated by protoc-gen-gogo.
// source: index.proto
// DO NOT EDIT!

/*
Package index is a generated protocol buffer package.

It is generated from these files:
	index.proto

It has these top-level messages:
	Record
*/
package index

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Record_Type int32

const (
	Record_Direct   Record_Type = 1
	Record_Indirect Record_Type = 2
)

var Record_Type_name = map[int32]string{
	1: "Direct",
	2: "Indirect",
}
var Record_Type_value = map[string]int32{
	"Direct":   1,
	"Indirect": 2,
}

func (x Record_Type) Enum() *Record_Type {
	p := new(Record_Type)
	*p = x
	return p
}
func (x Record_Type) String() string {
	return proto.EnumName(Record_Type_name, int32(x))
}
func (x *Record_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Record_Type_value, data, "Record_Type")
	if err != nil {
		return err
	}
	*x = Record_Type(value)
	return nil
}

type Record struct {
	Type             *Record_Type `protobuf:"varint,1,opt,name=type,enum=Record_Type" json:"type,omitempty"`
	Blocks           []uint64     `protobuf:"varint,2,rep,name=blocks" json:"blocks,omitempty"`
	Size_            *uint64      `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	Data             []byte       `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}

func (m *Record) GetType() Record_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Record_Direct
}

func (m *Record) GetBlocks() []uint64 {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *Record) GetSize_() uint64 {
	if m != nil && m.Size_ != nil {
		return *m.Size_
	}
	return 0
}

func (m *Record) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Record)(nil), "Record")
	proto.RegisterEnum("Record_Type", Record_Type_name, Record_Type_value)
}
