// Code generated by protoc-gen-gogo.
// source: index.proto
// DO NOT EDIT!

/*
Package index is a generated protocol buffer package.

It is generated from these files:
	index.proto

It has these top-level messages:
	Record
*/
package index

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Record_Type int32

const (
	Record_Direct   Record_Type = 1
	Record_Indirect Record_Type = 2
)

var Record_Type_name = map[int32]string{
	1: "Direct",
	2: "Indirect",
}
var Record_Type_value = map[string]int32{
	"Direct":   1,
	"Indirect": 2,
}

func (x Record_Type) Enum() *Record_Type {
	p := new(Record_Type)
	*p = x
	return p
}
func (x Record_Type) String() string {
	return proto.EnumName(Record_Type_name, int32(x))
}
func (x *Record_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Record_Type_value, data, "Record_Type")
	if err != nil {
		return err
	}
	*x = Record_Type(value)
	return nil
}
func (Record_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptorIndex, []int{0, 0} }

type Record struct {
	Type             *Record_Type `protobuf:"varint,1,opt,name=type,enum=Record_Type" json:"type,omitempty"`
	Blocks           []uint64     `protobuf:"varint,2,rep,name=blocks" json:"blocks,omitempty"`
	Size_            *uint64      `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	Data             []byte       `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Record) Reset()                    { *m = Record{} }
func (m *Record) String() string            { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()               {}
func (*Record) Descriptor() ([]byte, []int) { return fileDescriptorIndex, []int{0} }

func (m *Record) GetType() Record_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Record_Direct
}

func (m *Record) GetBlocks() []uint64 {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *Record) GetSize_() uint64 {
	if m != nil && m.Size_ != nil {
		return *m.Size_
	}
	return 0
}

func (m *Record) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Record)(nil), "Record")
	proto.RegisterEnum("Record_Type", Record_Type_name, Record_Type_value)
}

func init() { proto.RegisterFile("index.proto", fileDescriptorIndex) }

var fileDescriptorIndex = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xcc, 0x4b, 0x49,
	0xad, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xea, 0x61, 0xe4, 0x62, 0x0b, 0x4a, 0x4d, 0xce,
	0x2f, 0x4a, 0x11, 0x52, 0xe0, 0x62, 0x29, 0xa9, 0x2c, 0x48, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x33, 0xe2, 0xd1, 0x83, 0x08, 0xeb, 0x85, 0x54, 0x16, 0xa4, 0x06, 0x81, 0x65, 0x84, 0xc4, 0xb8,
	0xd8, 0x92, 0x72, 0xf2, 0x93, 0xb3, 0x8b, 0x25, 0x98, 0x14, 0x98, 0x35, 0x58, 0x82, 0xa0, 0x3c,
	0x21, 0x21, 0x2e, 0x96, 0xe2, 0xcc, 0xaa, 0x54, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x96, 0x20, 0x30,
	0x1b, 0x24, 0x96, 0x92, 0x58, 0x92, 0x28, 0xc1, 0xa2, 0xc0, 0xa8, 0xc1, 0x13, 0x04, 0x66, 0x2b,
	0x29, 0x70, 0xb1, 0x80, 0x4c, 0x13, 0xe2, 0xe2, 0x62, 0x73, 0xc9, 0x2c, 0x4a, 0x4d, 0x2e, 0x11,
	0x60, 0x14, 0xe2, 0xe1, 0xe2, 0xf0, 0xcc, 0x4b, 0x81, 0xf0, 0x98, 0x00, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xa7, 0xbf, 0x63, 0xf5, 0x9c, 0x00, 0x00, 0x00,
}
